#!/bin/sh -e

workspace_dir=$1
output_dir=$2

curl -s "ftp://sourceware.org/pub/libffi/libffi-${VERSION}.tar.gz" -o - | tar xzf - --strip-components=1
env CFLAGS=-fPIC ./configure --enable-static --disable-shared --prefix=${output_dir}
make
make install
# copy ffi headers in a place where ruby can find them
cp -r ${output_dir}/lib/libffi-${VERSION}/include ${output_dir}/
