user: rubies
group: rubies
cli: false
buildpack: https://github.com/pkgr/pkgr-source-buildpack
targets:
  debian-7:
  ubuntu-12.04:
  ubuntu-14.04:
  centos-6:
variants:
  "ruby-2.1":
    RUBIES: "2.1.5"
  "ruby-2.0":
    RUBIES: "2.0.0-p598"
  "ruby-1.9":
    RUBIES: "1.9.3-p551"
