#!/bin/bash

set -ex

BUILD_DIR="$1"
CACHE_DIR="$2"
ENV_DIR="$3"
RUBIES="2.1.4"

for ruby_version in $RUBIES ; do
	output_dir=$(mktemp -d)
	VERSION="$ruby_version" $BUILD_DIR/buildpack/build.rb "$BUILD_DIR" "$output_dir" "$CACHE_DIR"
	mkdir -p $BUILD_DIR/$ruby_version

	for file in $output_dir/*.tgz ; do
		tar xzf $file -C $BUILD_DIR/$ruby_version
	done
done
