#!/bin/bash

set -ex

BUILD_DIR="$1"
CACHE_DIR="$2"
ENV_DIR="$3"
RUBIES="2.1.4 2.0.0-p594 1.9.3-p550"

for ruby_version in $RUBIES ; do
	output_dir=$(mktemp -d)
	VERSION="$ruby_version" $BUILD_DIR/buildpack/build.rb "$BUILD_DIR" "$output_dir" "$CACHE_DIR"

	install_dir="$BUILD_DIR/${ruby_version/-*/}"
	mkdir -p "$install_dir"
	for file in $output_dir/*.tgz ; do
		tar xzf $file -C $install_dir
	done
	rm -f $install_dir/node

	chmod 0755 "$install_dir"
done

# install node in separate bin directory
mkdir -p "$BUILD_DIR/node/bin"
tar xzf $output_dir/node-*.tgz -C "$BUILD_DIR/node/bin/"
chmod 0755 "$BUILD_DIR/node/bin"

# clean up build dir
rm -rf $BUILD_DIR/{.gitignore,buildpack,patches,dependencies}
rm -rf $BUILD_DIR/ruby-*
