#!/bin/bash

set -ex

BUILD_DIR="$1"
CACHE_DIR="$2"
ENV_DIR="$3"
: ${RUBIES:?"Needs to set RUBIES"}

for ruby_version in $RUBIES ; do
	output_dir=$(mktemp -d)
	short_version="${ruby_version/-*/}"
	VERSION="$ruby_version" $BUILD_DIR/buildpack/build.rb "$BUILD_DIR" "$output_dir" "$CACHE_DIR"

	install_dir="$BUILD_DIR"
	mkdir -p "$install_dir"

	# for file in $output_dir/lib*.tgz ; do
	# 	tar xzf $file -C $install_dir
	# done

	tar xzf $output_dir/ruby-$short_version.tgz -C $install_dir

	for dir in $install_dir/lib/ruby/gems/* ; do
		tar xzf $output_dir/bundler-1.6.3.tgz -C $dir
		chmod 0755 "$dir"

		cat $BUILD_DIR/buildpack/gem_header.sh $dir/bin/bundle | tee $dir/bin/bundle &>/dev/null
		chmod 0755 $dir/bin/bundle
		ln -s "../lib/ruby/gems/$(basename $dir)/bin/bundle" $install_dir/bin/bundle
	done

	chmod 0755 "$install_dir"
done

# install node in separate bin directory
mkdir -p "$BUILD_DIR/node/bin"
tar xzf $output_dir/node-*.tgz -C "$BUILD_DIR/node/bin/"
chmod 0755 "$BUILD_DIR/node/bin"

# clean up build dir
rm -rf $BUILD_DIR/{.gitignore,buildpack,patches,dependencies,.pkgr.yml}
rm -rf $BUILD_DIR/ruby-*
